imports:
  - { resource:  'parameters.yml' }
framework:
  secret: %framework.secret%
  router:
    resource: %router.resource%
  assets: ~
  form: ~

services:
  Eccube\Core\Routing\CoreLoader:
    tags: ['routing.loader']
    arguments:
      - "@service_container"
      - "@routing.loader.yml"