imports:
  - { resource:  'parameters.yml' }
  - { resource:  'doctrine.yml' }
  - { resource:  'security.yml' }
  - { resource:  'services.yml' }

framework:
  secret: %framework.secret%
  router:
    resource: %router.resource%
  assets: ~
  form: ~
  session:
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'