imports:
  - { resource:  'parameters.yml' }

framework:
  secret: %framework.secret%
  router:
    resource: %router.resource%
  assets: ~
  form: ~
  session:
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
doctrine:
  dbal:
    driver: pdo_mysql
    host: %database_host%
    port: %database_port%
    dbname: %database_name%
    user: %database_user%
    password: %database_password%
    charset:  %database_charset%
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

services:
  Eccube\Core\Routing\CoreLoader:
    tags: ['routing.loader']
    arguments:
      - "@service_container"
      - "@routing.loader.yml"