security:
  providers:
    db_provider:
      entity:
        class: Eccube\User\Entity\User
        property: username

  firewalls:
    main:
      anonymous: ~
      provider: db_provider
      form_login:
        login_path: eccube_user_account_login
        check_path: eccube_user_account_login
        username_parameter: login[username]
        password_parameter: login[password]
      logout:
        path: /account/logout
        target: eccube_core_index_index

  encoders:
    Eccube\User\Entity\User: sha512

  access_control:
    - { path: ^/account/my-page, roles: ROLE_USER }